List P= 16F877A
#include P16F877A.inc

MAIN:
BANKSEL TRISB ;PORTB AS OUTPUT FOR SEVEN SEGNMENT LED
CLRF TRISB
MOVLW 0XFF  
MOVWF TRISC ;PORTC AS INPUT FOR RECEVING DATA FROM MASTER PIC


;---CONFIGURE SPBRG FOR DESIRED BAUD RATE
MOVLW D'51' ;WE WILL USE 4800bps 
MOVWF SPBRG ;BAUD AT 4MHZ

;---CONFIGURE TXSTA
MOVLW B'00100100' ;CONFIGURE TXSTA AS :
MOVWF TXSTA ;
;8 BIT TRANSMISSION - 6.BIT
;TRANSMIT ENABLED - 5.BIT
;ASYNCHRONOUS MODE - 4.BIT
;ENABLE HIGH SPEED BAUD RATE - 2.BIT

BCF STATUS,RP0 ;SWITCH TO BANK0

MOVLW B'10000000' ;ENABLE SERIAL PORT
MOVWF RCSTA ;RECEIVE STATUS REG

BSF INTCON,7 ;ENABLE ALL UNMASKED INTERRUPTS
BSF RCSTA,4 ;ENABLE USART RECEIVE

MAIN_LOOP: ;CONTINOUS LOOP
	GOTO MAIN_LOOP ;IF NOT GOTO CONTINOUS LOOP


INTERRUPT:
	BCF INTCON,7 ;DISABLE ALL INTERRUPTS
	BTFSS PIR1,5 ;CHECK IF THE RCIF FLAG IS SET

	RETFIE


DISPLAY: 
	; Displays the value at 0x20.
	MOVF 0X20, 0 ; Get the tranmitted keyboard value
	CALL DISPLAY_CODE ; get the corresponding value of diaplay
	MOVWF PORTC ; display the output to the 7SEG LED connected to portc
	RETURN
	
	DISPLAY_CODE:
		ADDWF PCL, 1 ; Add PCL plus the key value to display
				   ; HEX for
		RETLW 0XBF ; 0
		RETLW 0X86 ; 1
		RETLW 0XDB ; 2
		RETLW 0XCF ; 3
		RETLW 0XE6 ; 4
		RETLW 0XED ; 5
		RETLW 0XFD ; 6
		RETLW 0X87 ; 7
		RETLW 0XFF ; 8
		RETLW 0XEF ; 9
		RETLW 0XBF ; 0
		RETLW 0XEC ; S for star
		RETLW 0XF6 ; H for hash

TERMINATE:
END