List P= 16F877A
#include P16F877A.inc

ORG 0x000
GOTO MAIN ;MAIN PROGRAM

ORG 0x004 ;INTERRUPT 
BANKSEL PIR1
CHECK:
BTFSS PIR1, 5
GOTO CHECK
GOTO INTERRUPT

MAIN:
BANKSEL TRISB ;PORTB AS OUTPUT FOR SEVEN SEGNMENT LED
CLRF TRISB
MOVLW 0XFF  
MOVWF TRISC ;PORTC AS INPUT FOR RECEVING DATA FROM MASTER PIC


;---CONFIGURE PERIPHERAL INTERRUPTS
MOVLW B'00100000' ;DISABLE ALL PERIPHERAL INTERRUPTS EXCEPT RECEIVER
MOVWF PIE1 ;PERIPHERAL INTERRUPT ENABLE/DISABLE

;---CONFIGURE GENERAL INTERRUPTS
MOVLW B'01000000' ;DISABLE ALL INTERRUPTS EXCEPT PERIPHERAL
MOVWF INTCON ;INTERRUPT CONTROL REGISTER

;---CONFIGURE SPBRG FOR DESIRED BAUD RATE
MOVLW D'51' ;WE WILL USE 4800bps 
MOVWF SPBRG ;BAUD AT 4MHZ

;---CONFIGURE TXSTA
MOVLW B'00100100' ;CONFIGURE TXSTA AS :
MOVWF TXSTA ;
;8 BIT TRANSMISSION - 6.BIT
;TRANSMIT ENABLED - 5.BIT
;ASYNCHRONOUS MODE - 4.BIT
;ENABLE HIGH SPEED BAUD RATE - 2.BIT

BCF STATUS,RP0 ;SWITCH TO BANK0

MOVLW B'10000000' ;ENABLE SERIAL PORT
MOVWF RCSTA ;RECEIVE STATUS REG

BSF INTCON,7 ;ENABLE ALL UNMASKED INTERRUPTS
BSF RCSTA,4 ;ENABLE USART RECEIVE

MAIN_LOOP: ;CONTINOUS LOOP
	;BTFSC PORTB,4 ;CHECK IF THE BUTTON IS PRESSED
	GOTO MAIN_LOOP ;IF NOT GOTO CONTINOUS LOOP
	;MOVF TMP_TX,W ;LOAD TMP_TX  
	;MOVWF TXREG ;TO TXREG
	;WE LOAD TMP_TX ON THE INTERRUPT ROUTINE,
	;WHEN AN INFORMATION RECEIVED FROM RX.
	;GOTO MAIN_LOOP ;CONTINOUS LOOP

INTERRUPT:
	BCF INTCON,7 ;DISABLE ALL INTERRUPTS
	BTFSS PIR1,5 ;CHECK IF THE RCIF FLAG IS SET

	RETFIE




TERMINATE:
END